/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package sistemast2;

import java.net.MalformedURLException;
import java.rmi.Naming;
import java.rmi.RemoteException;
import java.rmi.registry.LocateRegistry;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Diogo
 */

public class JPanelServer extends javax.swing.JPanel {

    int numClientesEspera = 0;
    
    /**
     * Creates new form JPanel
     */
    
    public JPanelServer() {
        initComponents();
        iniciaControle();
    }

    public void iniciaControle(){
        try {
            IServer c = new ServerChat(listaAtLivres, listaAtOcupados, listaClientesEspera);
            LocateRegistry.createRegistry(56787);
            Naming.rebind("rmi://localhost:56787/ChatService", c);
            System.out.println(">> Inicia Servidor");
        } catch (RemoteException | MalformedURLException e) {
            e.printStackTrace();
        }
    }
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jScrollPane5 = new javax.swing.JScrollPane();
        listaClientesEspera = new javax.swing.JTable();
        jScrollPane6 = new javax.swing.JScrollPane();
        listaAtOcupados = new javax.swing.JTable();
        jScrollPane7 = new javax.swing.JScrollPane();
        listaAtLivres = new javax.swing.JTable();

        setMinimumSize(new java.awt.Dimension(820, 400));
        setPreferredSize(new java.awt.Dimension(820, 400));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setText("Atendentes Livres");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 40, -1, -1));

        jLabel2.setText("Clientes em Espera");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 40, -1, -1));

        jLabel3.setText("Atendentes Ocupados");
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 40, -1, -1));

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel4.setText("Servidor");
        add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 10, -1, -1));

        listaClientesEspera.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Nome"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane5.setViewportView(listaClientesEspera);
        if (listaClientesEspera.getColumnModel().getColumnCount() > 0) {
            listaClientesEspera.getColumnModel().getColumn(0).setPreferredWidth(10);
            listaClientesEspera.getColumnModel().getColumn(1).setResizable(false);
            listaClientesEspera.getColumnModel().getColumn(1).setPreferredWidth(100);
        }

        add(jScrollPane5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 60, 250, 210));

        listaAtOcupados.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Nome"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane6.setViewportView(listaAtOcupados);
        if (listaAtOcupados.getColumnModel().getColumnCount() > 0) {
            listaAtOcupados.getColumnModel().getColumn(0).setResizable(false);
            listaAtOcupados.getColumnModel().getColumn(0).setPreferredWidth(10);
            listaAtOcupados.getColumnModel().getColumn(1).setResizable(false);
            listaAtOcupados.getColumnModel().getColumn(1).setPreferredWidth(100);
        }

        add(jScrollPane6, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 60, 250, 210));

        listaAtLivres.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Nome"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane7.setViewportView(listaAtLivres);
        if (listaAtLivres.getColumnModel().getColumnCount() > 0) {
            listaAtLivres.getColumnModel().getColumn(0).setResizable(false);
            listaAtLivres.getColumnModel().getColumn(0).setPreferredWidth(10);
            listaAtLivres.getColumnModel().getColumn(1).setResizable(false);
            listaAtLivres.getColumnModel().getColumn(1).setPreferredWidth(100);
        }

        add(jScrollPane7, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 60, 250, 210));
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JScrollPane jScrollPane7;
    private javax.swing.JTable listaAtLivres;
    private javax.swing.JTable listaAtOcupados;
    private javax.swing.JTable listaClientesEspera;
    // End of variables declaration//GEN-END:variables
}
