/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package sistemast2;

import java.net.MalformedURLException;
import java.rmi.ConnectException;
import java.rmi.Naming;
import java.rmi.NotBoundException;
import java.rmi.RemoteException;
import java.text.SimpleDateFormat;
import java.util.Calendar;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JPanel;

/**
 *
 * @author Diogo
 */
public class JPanelAtendente extends javax.swing.JPanel {

    public JPanel tela2;
    
    public boolean conectou = false;
    public String nomeAtedente = "atendente";
    AtendentChat aChat = null;
    IChat conexao = null;
    IServer servidor;
    
    /**
     * Creates new form JPanel
     */
    public JPanelAtendente() {
        initComponents();
        iniciaControle();
    }   
    
    
    
    public void iniciaControle(){
        areaChat.setText(areaChat.getText()+"> Atendente Iniciado.\n");
        try {
            nomeLabel2.setText("");
            aChat = new AtendentChat(areaChat,conexao,buttonSend,buttonEncerrar,nomeLabel2);
            aChat.atendente = new Atendent(nomeAtedente);
            
            servidor = (IServer) Naming.lookup("rmi://localhost:56787/ChatService");
            areaChat.setText(areaChat.getText()+"> Servidor Conectado.\n");
            buttonSend.setEnabled(false);
            buttonEncerrar.setEnabled(false);
            areaChat.setText(areaChat.getText()+"> Aguardando Cliente.\n");
            servidor.requestJoin(aChat);

            nomeLabel1.setText(nomeAtedente+" "+aChat.atendente.getId());
            if(aChat.getConectado())
                nomeLabel2.setText(aChat.conexao.getName()+" "+aChat.conexao.getId());
            conectou = true;
            System.out.println("> Chamou [requestAtendent]");
        } catch (RemoteException | NotBoundException | MalformedURLException e) {
            e.printStackTrace();
            System.out.println("SISTEMA FORA DO AR");
            //this.setVisible(false);
            
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jScrollPane4 = new javax.swing.JScrollPane();
        areaChat = new javax.swing.JTextArea();
        buttonEncerrar = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        nomeLabel2 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        areaInput = new javax.swing.JTextArea();
        buttonSend = new javax.swing.JButton();
        close = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        nomeLabel1 = new javax.swing.JLabel();

        setMinimumSize(new java.awt.Dimension(520, 400));
        setPreferredSize(new java.awt.Dimension(550, 400));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setText("Chat");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 50, -1, -1));

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel4.setText("Atendente");
        add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 10, -1, -1));

        areaChat.setEditable(false);
        areaChat.setColumns(20);
        areaChat.setRows(5);
        jScrollPane4.setViewportView(areaChat);

        add(jScrollPane4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 70, 520, 200));

        buttonEncerrar.setText("Encerrar");
        buttonEncerrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonEncerrarActionPerformed(evt);
            }
        });
        add(buttonEncerrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 320, 100, 30));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel1.setText("Cliente:");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 40, -1, -1));

        nomeLabel2.setText("cliente 0");
        add(nomeLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 40, -1, 10));

        areaInput.setColumns(20);
        areaInput.setRows(4);
        jScrollPane1.setViewportView(areaInput);

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 280, 410, 70));

        buttonSend.setText("Enviar");
        buttonSend.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonSendActionPerformed(evt);
            }
        });
        add(buttonSend, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 280, 100, 30));

        close.setText("Fechar");
        close.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                closeActionPerformed(evt);
            }
        });
        add(close, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 10, -1, -1));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel3.setText("Meu nome:");
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 20, -1, -1));

        nomeLabel1.setText("atendente 0");
        add(nomeLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 20, -1, 10));
    }// </editor-fold>//GEN-END:initComponents

    private void buttonEncerrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonEncerrarActionPerformed
        //this.setVisible(false);
        
        buttonSend.setEnabled(false);
        buttonEncerrar.setEnabled(false);
        areaChat.setText(areaChat.getText()+"===> Atendimento Encerrado <===\n");
        areaChat.setText(areaChat.getText()+"> Aguardando novo cliente\n");
        try {
            aChat.conexao.closeConexao();
            servidor.freeAtendent(aChat);
        } catch (RemoteException ex) {
            ex.printStackTrace();
        }
    }//GEN-LAST:event_buttonEncerrarActionPerformed

    private void buttonSendActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonSendActionPerformed
        try {
            IMessage msg = new Message();
            msg.setMessage(areaInput.getText());
            Calendar c = Calendar.getInstance();
            msg.setDate(c);
            SimpleDateFormat ft = new SimpleDateFormat ("dd.MM.yyyy '/' HH:mm:ss");
            areaChat.setText(areaChat.getText()+" "+ft.format(c.getTime())+" | "+nomeAtedente+" > "+areaInput.getText()+"\n");
            aChat.conexao.deliver(msg);
            areaInput.setText("");
        } catch (RemoteException ex) {
            ex.printStackTrace();
        }
    }//GEN-LAST:event_buttonSendActionPerformed

    private void closeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_closeActionPerformed
        try {
            servidor.requestLeave(aChat);
        } catch (RemoteException ex) {
            Logger.getLogger(JPanelAtendente.class.getName()).log(Level.SEVERE, null, ex);
        }
        System.exit(0);
    }//GEN-LAST:event_closeActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextArea areaChat;
    private javax.swing.JTextArea areaInput;
    private javax.swing.JButton buttonEncerrar;
    private javax.swing.JButton buttonSend;
    private javax.swing.JButton close;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JLabel nomeLabel1;
    private javax.swing.JLabel nomeLabel2;
    // End of variables declaration//GEN-END:variables
}
