/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package sistemast2;

import java.net.MalformedURLException;
import java.rmi.ConnectException;
import java.rmi.Naming;
import java.rmi.NotBoundException;
import java.rmi.RemoteException;
import java.text.SimpleDateFormat;
import java.util.Calendar;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author Diogo
 */
public class JPanelCliente extends javax.swing.JPanel {

    public boolean conectou = false;
    public String nomeCliente = "cliente";
    public ClientChat cChat = null;
    public IChat conexao = null;
    public IServer servidor;
    
    /**
     * Creates new form JPanel
     */
    public JPanelCliente() {
        initComponents();
        iniciaControle();
    }
    
    public void iniciaControle(){
        areaChat.setText(areaChat.getText()+"> Cliente Iniciado.\n");
        try {
            nomeLabel2.setText("");
            cChat = new ClientChat(areaChat,buttonSend,nomeLabel2);
            cChat.cliente = new Client(nomeCliente);
            
            servidor = (IServer) Naming.lookup("rmi://localhost:56787/ChatService");
            areaChat.setText(areaChat.getText()+"> Servidor Conectado.\n");
            areaChat.setText(areaChat.getText()+"> Aguardando Atendente.\n");
            conexao = (IChat)servidor.requestAtendent(cChat);
            
            nomeLabel1.setText(nomeCliente+" "+cChat.cliente.getId());
            if(cChat.getConectado())
                nomeLabel2.setText(cChat.conexao.getName()+" "+cChat.conexao.getId());
            
            if(conexao != null){
                cChat.setConexao(conexao);
                conectou = true;
                conexao.setConexao(cChat);
                System.out.println("> Chamou [requestAtendent]");
            }
        } catch (Exception e) {
            e.printStackTrace();
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jScrollPane4 = new javax.swing.JScrollPane();
        areaChat = new javax.swing.JTextArea();
        buttonSend = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        nomeLabel2 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        areaInput = new javax.swing.JTextArea();
        jButton1 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        nomeLabel1 = new javax.swing.JLabel();

        setMinimumSize(new java.awt.Dimension(520, 400));
        setPreferredSize(new java.awt.Dimension(550, 400));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setText("Chat");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 50, -1, -1));

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel4.setText("Cliente");
        add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 10, -1, -1));

        areaChat.setEditable(false);
        areaChat.setColumns(20);
        areaChat.setRows(5);
        jScrollPane4.setViewportView(areaChat);

        add(jScrollPane4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 70, 520, 200));

        buttonSend.setText("Enviar");
        buttonSend.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonSendActionPerformed(evt);
            }
        });
        add(buttonSend, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 280, 100, 70));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel1.setText("Atendente:");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 40, -1, -1));

        nomeLabel2.setText("Atendente 0");
        add(nomeLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 40, -1, -1));

        areaInput.setColumns(20);
        areaInput.setRows(4);
        jScrollPane1.setViewportView(areaInput);

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 280, 410, 70));

        jButton1.setText("Fechar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 10, -1, -1));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel3.setText("Meu nome:");
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 20, -1, -1));

        nomeLabel1.setText("Cliente 0");
        add(nomeLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 20, -1, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void buttonSendActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonSendActionPerformed
        try {
            // TODO add your handling code here:
            IMessage msg = new Message();
            msg.setMessage(areaInput.getText());
            Calendar c = Calendar.getInstance();
            msg.setDate(c);
            SimpleDateFormat ft = new SimpleDateFormat ("dd.MM.yyyy '/' HH:mm:ss");
            areaChat.setText(areaChat.getText()+" "+ft.format(c.getTime())+" | "+nomeCliente+" > "+areaInput.getText()+"\n");
            cChat.conexao.deliver(msg);
            areaInput.setText("");
        } catch (RemoteException ex) {
            ex.printStackTrace();
        }
    }//GEN-LAST:event_buttonSendActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        try {
            if(cChat.getConectado()){
                cChat.conexao.closeConexao();
                servidor.freeAtendent(cChat.conexao);
            }
            cChat.closeConexao();
        } catch (RemoteException ex) {
            Logger.getLogger(JPanelCliente.class.getName()).log(Level.SEVERE, null, ex);
        }
        System.exit(0);
    }//GEN-LAST:event_jButton1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextArea areaChat;
    private javax.swing.JTextArea areaInput;
    private javax.swing.JButton buttonSend;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JLabel nomeLabel1;
    private javax.swing.JLabel nomeLabel2;
    // End of variables declaration//GEN-END:variables
}
